import { describe, expect, it } from "vitest";
import {
  encodeLeverage,
  encodeOrder,
  OrderType,
  Side,
  StpMode,
  TimeInForce,
  type OrderParams,
} from "./orderEncoding";

/**
 * Cross-check fixtures — generated by running risex-client's ORIGINAL
 * `ethers`-based encoder.ts logic (unmodified) against these exact inputs in a
 * throwaway script (not part of this repo), so this viem port can be verified
 * byte-for-byte rather than trusted on faith (docs/tasks.md task 6).
 */
const MARKET_BUY_EXAMPLE: OrderParams = {
  market_id: 2,
  size_steps: 1000,
  price_ticks: 0,
  side: Side.Long,
  order_type: OrderType.Market,
  time_in_force: TimeInForce.ImmediateOrCancel,
  post_only: false,
  reduce_only: false,
  stp_mode: StpMode.ExpireTaker,
  ttl_units: 0,
  builder_id: 0,
  client_order_id: "0",
};

const LIMIT_SELL_EXAMPLE: OrderParams = {
  market_id: 1,
  size_steps: 500,
  price_ticks: 640_000,
  side: Side.Short,
  order_type: OrderType.Limit,
  time_in_force: TimeInForce.GoodTillCancelled,
  post_only: true,
  reduce_only: true,
  stp_mode: StpMode.ExpireMaker,
  ttl_units: 0,
  builder_id: 0,
  client_order_id: "0",
};

describe("encodeOrder — cross-checked against risex-client's ethers implementation", () => {
  it("matches the reference hash for a market-buy IOC order", () => {
    expect(encodeOrder(MARKET_BUY_EXAMPLE)).toBe(
      "0x234077b59819bccb98693a8e6ea441e91ba29e3a78648bc2be0006a8dc843321",
    );
  });

  it("matches the reference hash for a post-only reduce-only limit-sell order", () => {
    expect(encodeOrder(LIMIT_SELL_EXAMPLE)).toBe(
      "0x609a999caa3741eac631ee5f7635cfe170e393690348cf4dbd6b218e2fc583e2",
    );
  });

  it("is deterministic (same input -> same hash)", () => {
    expect(encodeOrder(MARKET_BUY_EXAMPLE)).toBe(encodeOrder({ ...MARKET_BUY_EXAMPLE }));
  });

  it("changes the hash when any field changes (no accidental collisions in this suite)", () => {
    expect(encodeOrder(MARKET_BUY_EXAMPLE)).not.toBe(encodeOrder(LIMIT_SELL_EXAMPLE));
    expect(encodeOrder(MARKET_BUY_EXAMPLE)).not.toBe(
      encodeOrder({ ...MARKET_BUY_EXAMPLE, size_steps: 1001 }),
    );
    expect(encodeOrder(MARKET_BUY_EXAMPLE)).not.toBe(
      encodeOrder({ ...MARKET_BUY_EXAMPLE, reduce_only: true }),
    );
  });
});

/**
 * `encodeLeverage`'s formula was CORRECTED after a live "permit signature
 * mismatch" error on `/v1/account/leverage` (docs/tasks.md task 6 addendum):
 * `risex-client`'s version (`uint256(marketId) + uint128(leverage)`, no
 * action-type-hash prefix) was a real bug, not just a style difference. These
 * fixtures were regenerated from developer.rise.trade's documented formula
 * (`keccak256(abi.encode(keccak256("RISE_PERPS_UPDATE_LEVERAGE_V1"),
 * uint16(marketId), uint8(leverage)))`), cross-checked with an independent
 * `ethers`-based script (temporary, removed after use) — not trusted from the
 * SDK a second time.
 */
describe("encodeLeverage — cross-checked against the documented formula (not risex-client's, which was wrong)", () => {
  it("matches the reference hash for (marketId=2, leverage=5)", () => {
    expect(encodeLeverage(2, 5)).toBe(
      "0xb783755ca5686d91d078f74a1daa509d835e68b234621a9a8979119b815834c3",
    );
  });

  it("matches the reference hash for (marketId=1, leverage=10)", () => {
    expect(encodeLeverage(1, 10)).toBe(
      "0xc358a04124587a5809f1d6ddf57fc2ecb3d1691fd0a76a930c0518e961081880",
    );
  });

  it("matches the reference hash for (marketId=5, leverage=3)", () => {
    expect(encodeLeverage(5, 3)).toBe(
      "0x3a5efe4f51a72cada8fac44ae414a474ff1791735fd4353a7ad7529da13c5437",
    );
  });
});
